spring.application.name=unicare_backend

# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://manh:123@cluster0.ietrn0i.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=Unicare

unicare.app.jwtExpirationMs=86400000
unicare.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Logging
logging.level.org.springframework.data.mongodb=INFO

# VNPAY Configuration
vnp.pay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.tmn.code=R9HC6O18
vnp.hash.secret=Q2EPWORYU00EMSOVUZJ722GUQRKN9O2A
vnp.api.url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
vnp.return.url=http://localhost:5173/payment-result

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duonghoangmanh545@gmail.com
spring.mail.password=jskl hlaq xzke uwtl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
